#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 18 10:08:56 2018

@author: j
"""

print(list(map(lambda x: x**2, [1,2,3,4,5])))

print("****************************")

sq = lambda x: x**2
fact = lambda x: 1 if x==1 else x*fact(x-1)
f = [abs, int, sq, fact]
for func in f:
    print(func(5))
    
print("****************************")

